name: 'Setup Python'
description: 'Tag the current commit'
inputs:
  python-version:
    description: 'Python version to be used'
    required: true
  url:
    description: 'The url of the pypi repository'
    required: false
  user:
    description: 'The username to be used to connect to the pypi repository'
    required: false
  password:
    description: 'The password to be used to connect to the pypi repository'
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install poetry
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry

    - name: Configure remote in poetry
      if: ${{ inputs.url != '' }}
      shell: bash
      run: |
        poetry config repositories.my-remote ${{ inputs.url }}
        poetry config http-basic.my-remote ${{ inputs.user }} ${{ inputs.password }}

    - name: Install dependencies
      shell: bash
      run: poetry install
