name: 'Setup Python'
description: 'Tag the current commit'
inputs:
  python-version:
    description: 'Python version to be used'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install poetry
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry

    - name: Install dependencies
      shell: bash
      run: poetry install
